# Generated by Django 3.1 on 2022-04-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilities_name', models.CharField(max_length=20)),
                ('facilities_info', models.CharField(max_length=10)),
                ('facilities_note', models.CharField(max_length=10)),
            ],
        ),
    ]
