# Generated by Django 3.1 on 2022-04-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='facilities_note',
        ),
    ]
