# Generated by Django 3.1 on 2022-04-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_remove_facilities_facilities_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='Date',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='facilities_voltage',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
    ]
