# Generated by Django 3.1 on 2022-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0003_auto_20220429_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilities',
            old_name='facilities_voltage',
            new_name='Acce',
        ),
        migrations.RenameField(
            model_name='facilities',
            old_name='facilities_info',
            new_name='facilities_useage',
        ),
        migrations.AddField(
            model_name='facilities',
            name='Acce_X',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='Acce_Y',
            field=models.FloatField(default=2.3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='Acce_Z',
            field=models.FloatField(default=2.3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='Current',
            field=models.FloatField(default=2.6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='Power',
            field=models.FloatField(default=3.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='Temp',
            field=models.FloatField(default=3.26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='Voltage',
            field=models.FloatField(default=6.6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilities',
            name='battery',
            field=models.FloatField(default=99),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilities',
            name='Date',
            field=models.CharField(max_length=30),
        ),
    ]
