# Generated by Django 3.1 on 2022-08-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0005_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='facilities_firstfloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=30)),
                ('facilities_name', models.CharField(max_length=20)),
                ('facilities_useage', models.CharField(max_length=10)),
                ('battery', models.FloatField()),
                ('Acce_X', models.FloatField()),
                ('Acce_Y', models.FloatField()),
                ('Acce_Z', models.FloatField()),
                ('Acce', models.FloatField()),
                ('Temp', models.FloatField()),
                ('Current', models.FloatField()),
                ('Voltage', models.FloatField()),
                ('Power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='facilities_fourthfloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=30)),
                ('facilities_name', models.CharField(max_length=20)),
                ('facilities_useage', models.CharField(max_length=10)),
                ('battery', models.FloatField()),
                ('Acce_X', models.FloatField()),
                ('Acce_Y', models.FloatField()),
                ('Acce_Z', models.FloatField()),
                ('Acce', models.FloatField()),
                ('Temp', models.FloatField()),
                ('Current', models.FloatField()),
                ('Voltage', models.FloatField()),
                ('Power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='facilities_secondfloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=30)),
                ('facilities_name', models.CharField(max_length=20)),
                ('facilities_useage', models.CharField(max_length=10)),
                ('battery', models.FloatField()),
                ('Acce_X', models.FloatField()),
                ('Acce_Y', models.FloatField()),
                ('Acce_Z', models.FloatField()),
                ('Acce', models.FloatField()),
                ('Temp', models.FloatField()),
                ('Current', models.FloatField()),
                ('Voltage', models.FloatField()),
                ('Power', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='facilities_thirdfloor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=30)),
                ('facilities_name', models.CharField(max_length=20)),
                ('facilities_useage', models.CharField(max_length=10)),
                ('battery', models.FloatField()),
                ('Acce_X', models.FloatField()),
                ('Acce_Y', models.FloatField()),
                ('Acce_Z', models.FloatField()),
                ('Acce', models.FloatField()),
                ('Temp', models.FloatField()),
                ('Current', models.FloatField()),
                ('Voltage', models.FloatField()),
                ('Power', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='facilities',
            new_name='facilities_fifthfloor',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
